### ISSUE TITLE
Sending a PUT request to agents/~acl/ triggers validation of a cs:Agent resource

### ISSUE THREAD

**Issue by MiguelAraCo** [CarbonLDP/carbonldp-platform#1]

**Comment by MiguelAraCo** [comment]
Version `0.42.3` of the platform contains a fix for the bug. @enrique93 can you please corroborate that it fixes the problem?

**Comment by iamenrique** [comment]
The problem has been solved. The PUT request to `agents/~acl/` is no longer forbidden. THANKS!
